# **Systems of Linear Algebraic Equations**
Student name: Begantsova Milana

---
##Abstract
In this programming assignment I am going to implement Thomas and Gauss-Seidell alghorithms, that are used to solve systems of linear equations. I will study their perfomance (time-complexity) using defined tridiagonal matrix. Note that time-complexity of Gauss-Seidell method closely depends on precision of the result. So, I have decided to measure time needed for Gauss-Seidel method to achief the relatively the same precision as Thomas alghoritm. In this way, both alghoritms will be in the same conditions and their comparison will make sense.

The results of this assignment have shown that Thomas alghorithm perfomance is better than Gauss-Seidell in 6 times in terms of time-coplexity. This outcome cannot claim that on average Thomas alghoritms is faster than Gauss-Seidel (it is only one matrix studied). But asymptotic analysis has shown that Thomas alghoritm is faster.



---


##Introduction
Finding solutions of system of linear equations is usual task for data science and machine learning. So, any specialist should be able to apply different numerical methods to find uknows features.

In this programming assignment, we are going to be introduced two methods for finding solutions to such systems: Thomas alghoritm and Gauss-Seidel method. In the Part A, we are going to implement Thomas alghorithm and analyse what time is needed to find solution for defined matrix. In the Part B, we will do the same procedure with Gauss-Seidell method. In each of these parts, we should print our solutions. The solution for Gauss-Seidell should be given to the same precision as of Thomas alghoritms'solution. 

At the Part C, we should do asymptotic analysis to conclude what is the time complexity of both implementation. And then we will compare our prediction to the real result and conclude what alghoritm is more convinient to use.

---
##Methods
In this programming assignment, we are going to solve system of linear equation using two methods: Thomas alghorythm and Gauss-Seidell method. 

Thomas alghoritm is a linear alghoritms – $O(n)$, so it is fast compared with standart Gauss elimination – $O(n^3)$. Thomas alghorythm is used in tridiagonal matrix problems. Next condition ensures that alghorythm is stable:
$$|b_i|>|a_i|+|c_i|$$
Where, $b$ is main diagonal, $a$ and $c$ are upper and lower diagonal.
The incident when this condition is false happens rarely, usually pivoting may be helpful [1].

Gauss-Seidel method is an impoval of Gauss iteration method in terms of speed. It converges much faster as it uses previous approximations to compute new ones. This method does not accumulate round-off error, only round-off error of the last iteration matters. The time to converge depends on the precision that we would like to achief. As we try to solve a tridiagonal matrix problem, while solving system of equations I use value only from diagonals. So we do not need to iterate over each element of a row as in standart case, so I increased perfomance.

I will need to approximate Gauss-Seidell method to precision of Thomas Alghoritm, and I will do it by calculating absolute error.

I will use %timeit magic function to measure time perfomance of two alghoritms. This function is chosen because it does not require inluding any additional libraries, choses optimal number of iterations and we can store its result as timeit object. 

To ensure that calculations will be fast and more precise I will use numpy arrays and np.float128 datatype to store them. So, that I can decrease round-off error.


---
##Description
In this programming assignment, we will investigate algorithms for solving systems of linear equation, which are based on operations with matrices. The only library that we will need is `numpy`. They are faster than lists and have useful bult-in methods such as np.diagonal(), np.copy() that will be required during implementation. Also we will need fincding cross product of two matrices, which we also can do with numpy arrays.


In [ ]:
import numpy as np

The task of this assignment is to find solution to $A\times x=d$ system of linear equations. The matrix $A$ is written below:

$$A=\begin{bmatrix}
2.01475 & -0.020875 & 0 & 0\\
-0.020875 & 2.01475 & -0.020875 & 0\\
0 & -0.020875 & 2.01475 & -0.020875 \\
0 & 0 & -0.020875 & 2.01475
\end{bmatrix} $$

I store matrix $A$ as numpy array. The datatype of numpy array was changed to `np.float128`, so that we can store result with increased precision.

In [ ]:
matrix = np.array(
    [
      [2.01475, -0.020875, 0, 0],
      [-0.020875, 2.01475, -0.020875, 0],
      [0, -0.020875 , 2.01475 , -0.020875],
      [0, 0, -0.020875, 2.01475]
    ],
    dtype=np.float128)

As we can see, it is tridiagonal matrix. And it will make sense to work with diagonals only in both methods, as additional zeros will not contribute somehow in finding the solution to system. The diagonals can be extracted using function `np.diagonal(n)`, where n is an integer that indicates the right diagonal (negative n – diagonal is below than main one on abs(n) rows, positive n – diagonal is above). By default `np.diagonal()` returns values from main diagonal.

In [ ]:
a = matrix.diagonal(-1)
b = matrix.diagonal()
c = matrix.diagonal(1)

$$ \begin{bmatrix}
2.01475 & -0.020875 & 0 & 0\\
-0.020875 & 2.01475 & -0.020875 & 0\\
0 & -0.020875 & 2.01475 & -0.020875 \\
0 & 0 & -0.020875 & 2.01475
\end{bmatrix} 
\begin{Bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4 
\end{Bmatrix}=
\begin{Bmatrix}
4.175 \\
0 \\
0 \\
2.0875 
\end{Bmatrix}$$

In [ ]:
d = np.array([4.175, 0, 0, 2.0875], dtype=np.float128)

Both Thomas and Gauss-Seidell alghoritms should output numpy array $x$ with approximated solution to the system.

###Part A – Thomas Alghoritm
Thomas alghoritm is gausian elimination method that is adupted for solving tridioganal matrices. The method can be devided into two steps: forward elimination and backward substitution. 
<center>
<img src='https://www.cfd-online.com/W/images/math/5/b/7/5b73418f4d5bd7154e369a6d6f4ae2fd.png'>
<p>Figure 1 – Tridiagonal matrix</p>
</center>

While forward elimination step, we eleminate lower diagonal  and recalculate coefficients. You can see the pseudocode for Thomas alghorythm below [2]:

Pseudo code:

`For k=2 step 1 until n do:`
$$m=\frac{c_{k-1}}{b_{k-1}}$$
$$b_k=b_k-m\cdot a_{k-1}$$
$$d_k=d_k-m\cdot d_{k-1}$$


While backward substitution, we calculate values for $x$ in inverse order. As we have eliminated the lower diagonal, now values of $x$ depend only on upper and main diagonal. The formula for $x$ can be proofed mathematically.

Pseudo code:

$$x = d/b$$
`For k=n-1 step -1 until 1 do:`
$$x_k=\frac{d_k-c_k\cdot x_{k+1}}{b_k}$$



In [ ]:
def thomas_alghoritm(a, b, c, d):
  
  num_rows = len(d)
  
  #forward elimination
  for i in range(1, num_rows):
    gamma = c[i-1]/b[i-1]
    b[i] = b[i] - gamma*a[i-1] 
    d[i] = d[i] - gamma*d[i-1]
  
  x = d
  x[-1]/=b[-1]

  #backward substitution
  for i in range(num_rows-2, -1, -1):
      x[i] = (d[i]-c[i]*x[i+1])/b[i]

  return x
      

The function `thomas_alghorythm()` returns the array $x$, which is our solution. Problem definition requires to print us our solution properly.

In [ ]:
def print_solution(x):
  for i, item in enumerate(x):
    print(f"x_{i+1} = {item}")

At the beginning of the experiment, we have extracted diagonals from the matrix. I will transfer to function the copies of these arrays, as our function changes original values. 

The time perfomance of alghoritm will be measured using built-in magic function %timeit -o (-o states that function will return timeit object which stores the result). Timeit itself will determine how many iterations are sufficient to check average time perfomance.

In [ ]:
time_thomas = %timeit -o thomas_alghoritm(a.copy(), b.copy(), c.copy(), d.copy())

The slowest run took 60.97 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 10.8 µs per loop


The matrix meets the condiition of stability of Thomas alghorythm, so everything should be fine:

In [62]:
matrix

array([[ 2.01475 , -0.020875,  0.      ,  0.      ],
       [-0.020875,  2.01475 , -0.020875,  0.      ],
       [ 0.      , -0.020875,  2.01475 , -0.020875],
       [ 0.      ,  0.      , -0.020875,  2.01475 ]], dtype=float128)

In [ ]:
x_thomas = thomas_alghoritm(a.copy(), b.copy(), c.copy(), d.copy())

In [ ]:
print_solution(x_thomas)

x_1 = 2.072441054231562
x_2 = 0.021586300025824064
x_3 = 0.010960046464439314
x_4 = 1.0362222563444325


Now, it is time to check how well Thomas alghoritm identified values for $x$. I would like to remind that we solve equation of form $A\times x=d$. So cross product of matrix $A$ and $x$ should equal approximately $d$.

In [ ]:
def check(x, matrix, d):
  for i, item in enumerate(matrix@x):
    print(f"p_{i+1} = {item}, real = {d[i]}")


If we compare approximated result with real one, we will see that the solution preciseness is limited only by round-off error and truncation error. The results are almost the same if we consider `np.float128` as precise datatype.

In [ ]:
check(x_thomas, matrix.copy(), d)

p_1 = 4.175, real = 4.175
p_2 = 4.0763460586613204e-21, real = 0.0
p_3 = 0.0, real = 0.0
p_4 = 2.0875, real = 2.0875


###Part B – Gauss-Seidell
The problem definition asks us to calculate solutions with Gauss-Seidell method with the same precision as solution of Thomas alghoritm. 

If approximated solution of system of linear equations is right, then:
$$A\times x\approx d$$
I will judge the precision as absolute error.

In [ ]:
def check_precision(x_gauss, x_thomas, matrix):
  result_1 = matrix@x_gauss
  result_2 = matrix@x_thomas
  return abs(result_1-result_2)

In order to understand the formula, see Figure 1.
Gauss-Seidell alghoritm is iterative method [3], where $x$ is calculated as

```
for i=1 to N step 1 do
  for k=1 to n step 1 do
```
$$x_k = \frac{d_k - x_{k-1}c_{k-1}-x_{k+1}a_{k}}{b_{k}}$$
```
  endfor
endfor
```
At first, all values of array $x$ are equal to zero. Then $x$ is mupltiple times recalculated until needed precicion is achieved. $N$ is the number of iterations, $n$ - number of rows.

In [ ]:
def gauss_seidell_alghoritm(a, b, c, d, iter):
  
  num_rows = len(d)
  x=np.zeros(num_rows, dtype=np.float128)
 
  for j in range(iter):
    for i in range(num_rows):
        
        x[i] = d[i]
        
        if i-1 >= 0: x[i]-= x[i-1]*c[i-1]
        if i+1 < num_rows: x[i]-= x[i+1]*a[i]
        
        x[i]/= b[i]
  
  return x

At first we need to identify how many iterations will allow Gauss-Seidell method to converge to relatively the same precision as of Thomas alghoritm. I assume that Gauss-Seidell method converges fast, so I will check how the error increases/decreases with number of iterations.

In [ ]:
def find_iter(a, b, c, d):
  for i in range(1,10):
    print(f"Iteration #{i}")
    x = gauss_seidell_alghoritm(a.copy(), b.copy(), c.copy(), d.copy(), i)
    print(check_precision(x, x_thomas, matrix))

In [ ]:
find_iter(a, b, c, d)

Iteration #1
[4.48195116e-04 4.64378858e-06 2.16288172e-02 2.16840434e-19]
Iteration #2
[9.62293948e-08 2.24099053e-04 2.32190978e-06 2.16840434e-19]
Iteration #3
[2.32192011e-06 4.81151255e-08 4.98525001e-10 2.16840434e-19]
Iteration #4
[7.47788056e-10 1.29131580e-11 1.33794351e-13 2.16840434e-19]
Iteration #5
[2.14070948e-13 3.60426830e-15 3.73439886e-17 2.16840434e-19]
Iteration #6
[6.02816408e-17 1.01614837e-18 8.47032947e-21 2.16840434e-19]
Iteration #7
[0.00000000e+00 6.76302869e-21 0.00000000e+00 2.16840434e-19]
Iteration #8
[0.00000000e+00 6.76302869e-21 0.00000000e+00 2.16840434e-19]
Iteration #9
[0.00000000e+00 6.76302869e-21 0.00000000e+00 2.16840434e-19]


It seems that after 7 iterations the absolute error does not change much. I can conclude that 7 iterations is enough.

In [ ]:
iter = 7

The aim of this experiment is to compare perfomance of two methods, I claim that Gauss-Seidell will be slower. I will save the result of testing to `time_gauss` variable.

In [ ]:
time_gauss = %timeit -o gauss_seidell_alghoritm(a.copy(), b.copy(), c.copy(), d.copy(), iter)

10000 loops, best of 3: 56.1 µs per loop


In [ ]:
x_gauss = gauss_seidell_alghoritm(a.copy(), b.copy(), c.copy(), d.copy(), iter)

The final solution of Gauss-Seidel method:

In [ ]:
print_solution(x_gauss)

x_1 = 2.072441054231562
x_2 = 0.021586300025824064
x_3 = 0.010960046464439314
x_4 = 1.0362222563444325


Now, I will do the same check as in Thomas alghoritm to ensure that $A\times x\approx d$

In [ ]:
check(x_gauss, matrix, d)

p_1 = 4.175, real = 4.175
p_2 = -2.686682629572234e-21, real = 0.0
p_3 = 0.0, real = 0.0
p_4 = 2.0875, real = 2.0875


The result's preciseness is limited by round-off error and number of significant figures. Gauss-Seidell methods's solution is slightly more precise.

###Part C – Asymphtotic analysis of two methods and their comparison
Before comparing the time of Thomas Alghoritm and Gauss-Seidell method, I would to theoreticalle forecast the time-coplexity of two functions using asymphtotic analysis.

Thomas alghorithm forward elimination step require:
1. 2(n-1) substractions
2. 2(n-1) multiplications
3. n-1 devisions

The backward substitution step require:
1. n-1 substraction
2. n-1 multiplication
3. n-1 devision

In total time complexity of Thomas alghorith is $T(n)=8n+C$, where $C$ is some constant.

The inner loop in Gauss-Seidell method require 2(n-1) substractions and mupltiplications, n devisions, 2n comparisons. This inner loop is repeated 7 times (we analysed it in practice).
In total time complexity of Gauss-Seidell method  is $T(n)=49n+K$, where $K$ is some constant. This is time comple



I forecast that Thomas alghoritm should be approximately 6 times faster than Gauss-Seidell method if we ignore constant operations.

In [ ]:
print(f"The Thomas alghoritm execution time: {time_thomas.best} s\nGauss-Seidell time: {time_gauss.best} s")
print(f"The Thomas alghoritm is faster in {time_gauss.best/time_thomas.best} times than of Gauss-Seidell method.")

The Thomas alghoritm execution time: 1.0754351739997218e-05 s
Gauss-Seidell time: 5.6093152900029965e-05 s
The Thomas alghoritm is faster in 5.215856265088506 times than of Gauss-Seidell method.


In practice the Thomas alghoritm is faster then Gauss-Seidell method in $\approx 5.5$ times, which is close to my theoretical prognose. However, I should note that it is valid only for our system with 4 equations. From this experiment, I cannot conclude how many iterations of outer loop are needed for Gauss-Seidel to converge to precision of Thomas alghoritm if we will have greater number of equations (maybe this number increases linearly or quadtratically). 

---
##Conclusion
In this programming assignment we used two numerical methods to find approximate solutions to the systems of linear equations. We were give a tridigonal matrix problem. Here are solutions provided by Thomas alghorytm and Gauss-Seidell method:


In [ ]:
print_solution(x_thomas)

x_1 = 2.072441054231562
x_2 = 0.021586300025824064
x_3 = 0.010960046464439314
x_4 = 1.0362222563444325


In [ ]:
print_solution(x_gauss)

x_1 = 2.072441054231562
x_2 = 0.021586300025824064
x_3 = 0.010960046464439314
x_4 = 1.0362222563444325


In [61]:
print(f"In our case, Thomas alghorithm was {(time_gauss.best/time_thomas.best):.2f} times faster than Gauss-Seidell, which confirms our theoretical assumption.") 

In our case, Thomas alghorithm was 5.22 times faster than Gauss-Seidell, which confirms our theoretical assumption.


The result showed that, for tridiagonal matrix problem, Thomas alghorytm is faster and more convinient. In the beginning I have mentioned that in Gauss-Seidell method I do not iterate over elements of each row, I use only values from diagonal instead. Even with this adapatation to tridiagonal matrix problem, the speed of Gauss-Seidell method is still lower.

In the future, to study those alghorythms I propose to randomly generate tridiagonal matrixes of different sizes. This matrixes will be used to make more reliable conclusion about convergence rate of Gauss-Seidell method.

##Links
[1] http://www.industrial-maths.com/ms6021_thomas.pdf

[2] https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm

[3] https://math.berkeley.edu/~wilken/228A.F07/chr_lecture.pdf